name: My First Action
on: [push]

jobs:
  check-version:      
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Check Go version
        run: go version